### ISSUE TITLE
Container is not defined

### ISSUE THREAD

**Issue by theaarontaylor** [devstark-com/vue-google-charts#3]
Hi, I'm getting a bunch of errors when I try to display the map. The weird thing is that it works in development but doesn't in production. The errors are as follows:

![screen shot 2018-06-18 at 1 17 27 pm](https://user-images.githubusercontent.com/7313352/41531007-aefa174c-72fa-11e8-88bc-f70dc0bebcee.png)

And my component looks like this. (Rows is filled on mounted):

`  <GChart
  type="GeoChart"
  :data="this.rows"
  :options="chartOptions"/>`

```
  data() {
    return {
      chartOptions: {
          title: 'Blocked IPs by Country',
          width: '80%',
          height: 600,
          colorAxis: {colors: ['#F990A9', '#fc4a74']},
      },
      rows: [],
      isBusy: false
  }
},
```

Is there something I'm doing wrong?

Thanks

**Comment by alexxlagutin** [comment]
@theaarontaylor Hi! We can`t reproduce the error with container. But you may get these errors because of usage 'mounted' to get rows. Try to use 'created' hook or computed property. Also you don`t need to use 'this.rows' in template, use 'rows' without 'this' instead. Also, please add to chartOptions  packages: ['geochart']. If these steps wont help you, please send us more details how to reproduce the bug ( maybe copy of your project )

**Comment by theaarontaylor** [comment]
We just solved it. I'll post the solution if anyone else runs into it. The first error has to do with Rocket Loader by CloudFlare. All we had to do was disable Rocket Loader in CloudFlare and it worked right away.
